### PR TITLE
Use u-boot version with patches for newer QEMU

### PR DESCRIPTION
**Pull request by OYTIS**

### CODE REVIEW

**Comment by leon-anavi** [comment]
Hi @OYTIS, looks good to me. I am running a Poky build right now to test in conjunction with the GitHub PR #16 from meta-updater-qemux86-64.

Best regards,
Leon

**Comment by leon-anavi** [comment]
I am experiencing the issue with multilib version while building U-Boot. As far as I remember we had similar issues in the past:

```
| arch/x86/lib/built-in.o: In function `__wrap___udivdi3':
| /media/storage/poky-qemu-test/build/tmp/work/qemux86_64-poky-linux/u-boot/1_2017.09-r0/git/arch/x86/lib/gcc.c:25: undefined reference to `__normal___udivdi3'
| /media/storage/poky-qemu-test/build/tmp/work/qemux86_64-poky-linux/u-boot/1_2017.09-r0/git/Makefile:1255: recipe for target 'u-boot' failed
| make[1]: *** [u-boot] Error 1
| make[1]: Leaving directory '/media/storage/poky-qemu-test/build/tmp/work/qemux86_64-poky-linux/u-boot/1_2017.09-r0/build'
| ERROR: oe_runmake failed
| Makefile:150: recipe for target 'sub-make' failed
| make: *** [sub-make] Error 2
| make: Leaving directory '/media/storage/poky-qemu-test/build/tmp/work/qemux86_64-poky-linux/u-boot/1_2017.09-r0/git'
| WARNING: /media/storage/poky-qemu-test/build/tmp/work/qemux86_64-poky-linux/u-boot/1_2017.09-r0/temp/run.do_compile.31783:1 exit 1 from 'exit 1'
| ERROR: Function failed: do_compile (log file is located at /media/storage/poky-qemu-test/build/tmp/work/qemux86_64-poky-linux/u-boot/1_2017.09-r0/temp/log.do_compile.31783)
ERROR: Task (/media/storage/poky-qemu-test/poky/meta/recipes-bsp/u-boot/u-boot_2017.09.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 2383 tasks of which 12 didn't need to be rerun and 1 failed.
```

Best regards, Leon

**Comment by patrickvacek** [comment]
Anton's suggestion for me was `HOSTTOOLS += "x86_64-linux-gnu-gcc"`, which solved some problems, but now I see things like this that we haven't been able to fix yet:

**Comment by patrickvacek** [comment]
Just realized my bug was previously logged as its own ticket in Jira that I'd forgotten about: https://advancedtelematic.atlassian.net/browse/PRO-4337

**Comment by leon-anavi** [comment]
It is OK using rocko branch of meta-updater-qemux86-64 and HOSTTOOLS += "x86_64-linux-gnu-gcc" in local/conf.local. I am a little concerned because HOSTTOOLS specifies a list of host-side tools and on other build configurations it might not work so well.

Best regards, Leon

**Pull request merged**
