### PR TITLE
Ci on thud

### PR DESCRIPTION
**Pull request by lbonn**

### CODE REVIEW

**Comment by lbonn** [comment]
Blocked by #549

**Comment by lbonn** [comment]
Blocked by https://github.com/advancedtelematic/updater-repo/pull/27

**Comment by patrickvacek** [comment]
> Blocked by [advancedtelematic/updater-repo#27](https://github.com/advancedtelematic/updater-repo/pull/27)

Why? But anyway, I think this will require at least a bitbake with this to test that it's okay.

**Comment by lbonn** [comment]
> > Blocked by [advancedtelematic/updater-repo#27](https://github.com/advancedtelematic/updater-repo/pull/27)
> 
> Why?

https://main.gitlab.in.here.com/olp/edge/ota/connect/client/meta-updater/-/jobs/210537

But ok, that's a good chance to test the pin feature.

**Comment by lbonn** [comment]
Well, also depend on https://github.com/advancedtelematic/meta-updater/pull/551 now :smile:

**Comment by lbonn** [comment]
This pipeline is running with `PIN_LIST=meta-raspberrypi:89bdf97beaf3b136c24c4d6f86c0bcbb47fe3043` (current thud): https://main.gitlab.in.here.com/olp/edge/ota/connect/client/meta-updater/pipelines/48770

**Comment by lbonn** [comment]
A minnowboard issue, like on #541... Will have a quick look.

**Comment by lbonn** [comment]
Great, should be good to merge now. CI should succeed any minute.

**Pull request merged**
