### PR TITLE
Trigger otf bitbake tests on PR

### PR DESCRIPTION
**Pull request by Raigi**
Not completely sure, how you create PRs here.. Let me know if this is correct, then I will create also for other branches and projects

### CODE REVIEW

**Comment by patrickvacek** [comment]
Normally we add new work to master and then backport, but this is probably fine for now. Seems okay to me and appears to be working. @lbonn do you have any further thoughts here?

**Comment by Raigi** [comment]
> Normally we add new work to master and then backport, but this is probably fine for now. Seems okay to me and appears to be working. @lbonn do you have any further thoughts here?

Not sure if we want to run otf on master PRs?

**Comment by patrickvacek** [comment]
> Not sure if we want to run otf on master PRs?

Up to you. I can understand why you'd prefer to only run it on release branch (backport) PRs. Maybe we only do that for now and reevaluate later if we want more.

**Comment by Raigi** [comment]
> > Not sure if we want to run otf on master PRs?
> 
> Up to you. I can understand why you'd prefer to only run it on release branch (backport) PRs. Maybe we only do that for now and reevaluate later if we want more.

Sounds good to me.

**Comment by patrickvacek** [comment]
Uh-oh, the trigger failed.

**Comment by Raigi** [comment]
> Uh-oh, the trigger failed.

yes, it is trying to do smth with docker, which otf build machine doesn't need. @lbonn any ideas?

**Comment by Raigi** [comment]
The pipeline got triggered now :)

**Pull request merged**
