### PR TITLE
(rocko) softhsm-testtoken: Update paths for token import.

### PR DESCRIPTION
**Pull request by lbonn**
And bump aktualizr recipe

### CODE REVIEW

**Comment by lbonn** [comment]
@patrickvacek maybe we can wait for the `installed_versions` changes before doing too much qa (also coming soon).

**Comment by lbonn** [comment]
Here is the other change that will also come to rocko at some point: https://github.com/advancedtelematic/meta-updater/pull/390

**Comment by patrickvacek** [comment]
@lbonn @EpicNuts sure, let's wait until that is ready. I'd love to have that taken care of!

**Comment by patrickvacek** [comment]
Closing because I've superseded this with a new PR with more backports: https://github.com/advancedtelematic/meta-updater/pull/396

**Pull request closed without merging**
