### PR TITLE
CI on rocko

### PR DESCRIPTION
**Pull request by lbonn**

### CODE REVIEW

**Comment by lbonn** [comment]
I've used another way: include pipelines and test scripts from the master branch so that we don't have to back-port every ci enhancements to all release branches.

**Comment by lbonn** [comment]
Passes oe-selftest ;). CI has been re-triggered by mistake, looking into that...

**Comment by lbonn** [comment]
> Cool! Officially, this should get QA'd, although it actually doesn't affect anything except tests and CI.

There are changes to `envsetup.sh` and the qemu run scripts, so maybe it's still worth checking that an image can be built and run.

**Comment by Raigi** [comment]
> > Cool! Officially, this should get QA'd, although it actually doesn't affect anything except tests and CI.
> 
> There are changes to `envsetup.sh` and the qemu run scripts, so maybe it's still worth checking that an image can be built and run.
> 
> No need to run oe-selftest obviously, though.

Ran bitbake for qemu, which was successful + device was created and provisioned successfully on server.

**Pull request merged**
