### PR TITLE
Feat/pro tech #1 sumo

### PR DESCRIPTION
**Pull request by patrickvacek**
Sprint release candidate.

### CODE REVIEW

**Comment by cajun-rat** [comment]
I'm still getting hsm and implicit provisioning test failures.  Will try with the plain 'sumo' branch and see if it is new.

**Comment by cajun-rat** [comment]
This seems to have broken the `updater.HsmTests` test.  It works on the current sumo but not with this patch.  I tried cleaning the openssl/openssl-native recipes, but that didn't seem to fix the problem.

**Comment by lbonn** [comment]
Maybe #363 is also affected by the HSM test failure? I'm running the tests right now

**Comment by cajun-rat** [comment]
Looks like the HSM failure is real.  Let's hold off merging this (and the Rocko one) until we can resolve that.

**Pull request merged**
