### PR TITLE
Move OSTREE_BRANCHNAME to image_types_ostree.bbclass.

### PR DESCRIPTION
**Pull request by patrickvacek**
If it is set in sota.bbclass and overwritten in local.conf, bitbake will rebuild everything. Now bitbake should only rerun the commands in image_types_ostree (and image_types_ota) as expected.

@Raigi can you confirm that this improves the OTF bitbake time when only changing the `OSTREE_BRANCHNAME`?

### CODE REVIEW

**Comment by patrickvacek** [comment]
I'm actually still not sure this is doing the trick for Raigi. It needs further investigation, but this probably shouldn't hurt.

**Comment by lbonn** [comment]
Ah my bad, I thought you verified it locally.

**Comment by Raigi** [comment]
> I'm actually still not sure this is doing the trick for Raigi. It needs further investigation, but this probably shouldn't hurt.

It didn't improve build time for me unfortunately, when I built locally or with otf.

**Comment by patrickvacek** [comment]
> It didn't improve build time for me unfortunately, when I built locally or with otf.

This is so strange. I just tried on shovel again and it worked for me. Did you have any luck with the bitbake you did on Friday?

Just to confirm, the steps I'm following are this:
1. Check out this branch (well, now it's on master, so that'll work too)
2. Bitbake without `OSTREE_BRANCHNAME` set. It should take a long time.
3. Change `OSTREE_BRANCHNAME` and bitbake again. It should only redo the garage-push/sign bits.

**Comment by Raigi** [comment]
> This is so strange. I just tried on shovel again and it worked for me. Did you have any luck with the bitbake you did on Friday?
> 
> Just to confirm, the steps I'm following are this:
> 
>     1. Check out this branch (well, now it's on master, so that'll work too)
> 
>     2. Bitbake without `OSTREE_BRANCHNAME` set. It should take a long time.
> 
>     3. Change `OSTREE_BRANCHNAME` and bitbake again. It should only redo the garage-push/sign bits.


No luck on Friday. Just tried with the above steps, doesn't seem to have any effect, the moment I add OSTREE_BRANCHNAME it starts bitbaking the whole thing.

**Comment by Raigi** [comment]
> > This is so strange. I just tried on shovel again and it worked for me. Did you have any luck with the bitbake you did on Friday?
> > Just to confirm, the steps I'm following are this:
> > ```
> > 1. Check out this branch (well, now it's on master, so that'll work too)
> > 
> > 2. Bitbake without `OSTREE_BRANCHNAME` set. It should take a long time.
> > 
> > 3. Change `OSTREE_BRANCHNAME` and bitbake again. It should only redo the garage-push/sign bits.
> > ```
> 
> No luck on Friday. Just tried with the above steps, doesn't seem to have any effect, the moment I add OSTREE_BRANCHNAME it starts bitbaking the whole thing.

The problem was with build setup on my machine for master branch, thanks to @patrickvacek it is fixed now and building with OSTREE_BRANCHNAME is super fast.

**Pull request merged**
