### PR TITLE
Follow Filesystem Hierarchy Standard

### PR DESCRIPTION
**Pull request by agners**
This aligns the OSTree rootfs output to be closer to what is documented in the OSTree documentation and the Filesystem Hierarchy Standard:

https://ostree.readthedocs.io/en/latest/manual/adapting-existing/

### CODE REVIEW

**Comment by patrickvacek** [comment]
Thanks! This looks like a good idea. @lbonn how hard is it to trigger CI on this? :)

**Comment by lbonn** [comment]
Hm for now (until we have a bot for that), you can push it to a gitlab branch and then launch it with the green button "Run pipeline" in CI/CD > Pipelines.

**Comment by patrickvacek** [comment]
@agners Running tests now, but I had to rebase your changes on latest master. Would you mind doing that?

**Comment by patrickvacek** [comment]
@lbonn [qemux86-64 passed](https://main.gitlab.in.here.com/olp/edge/ota/connect/client/meta-updater/pipelines/49500), but rpi and minnowboard didn't run. How do I get those to run?

**Comment by lbonn** [comment]
Ah sorry... I haven't enabled them by default on master, you'll have to launch a pipeline with the variables assignment: `OE_MINNOWBOARD = 1`, `OE_RPI = 1` and `OE_PTEST = 1` if you want ptest.
They run by default on release branches though.

**Pull request merged**
