### PR TITLE
Simplify OTA class

### PR DESCRIPTION
**Pull request by agners**
No functional change.

### CODE REVIEW

**Comment by lbonn** [comment]
Thanks, this looks good! I'm running tests now to make sure everything is in order.

**Comment by agners** [comment]
Ok, I did sign the CLA, although I am really not to happy about it. Also, this talk summarizes that CLA is not a good solution: https://connect.linaro.org/resources/yvr18/yvr18-200k2/

**Comment by agners** [comment]
@lbonn any update on this pull request?

**Comment by lbonn** [comment]
Everything checks out, thanks again.

Enforcing CLA for open source projects is part of our current company policy, I will pass along your concern internally.

**Comment by patrickvacek** [comment]
@agners @Jmennius @LukaPivk We have heard your concern and as an organization we have decided to move to DCOs. We are in the process of converting our repos now. Thanks again for bringing it up!

**Comment by agners** [comment]
@patrickvacek very cool, thank you for reconsider and move to DCO!

**Pull request merged**
