### PR TITLE
Zeus gitlab pipeline definitions

### PR DESCRIPTION
**Pull request by lbonn**

### CODE REVIEW

**Comment by patrickvacek** [comment]
Qemu and minnowboard as well?

**Comment by lbonn** [comment]
I noticed that we actually don't have pipelines for thud and warrior either on the qemu and minnowboard repos. I could go ahead and open the 6 PRs though

**Comment by patrickvacek** [comment]
> I noticed that we actually don't have pipelines for thud and warrior either on the qemu and minnowboard repos. I could go ahead and open the 6 PRs though

Do you mean nightly runs in CI, or just to run on new PRs? Mike set up the latter just recently and I backported that to thud and warrior. If the former, shouldn't the existing nightly runs of meta-updater take care of that?

**Comment by lbonn** [comment]
> Do you mean nightly runs in CI, or just to run on new PRs? Mike set up the latter just recently and I backported that to thud and warrior. If the former, shouldn't the existing nightly runs of meta-updater take care of that?

I meant for PRs but nevermind, I was looking at the wrong place... Sorry

**Pull request merged**
