### PR TITLE
fix: run aktualizr service after network is online

### PR DESCRIPTION
**Pull request by mike-sul**
Signed-off-by: Mykhaylo Sul <ext-mykhaylo.sul@here.com>

### CODE REVIEW

**Comment by mike-sul** [comment]
@Raigi Could you please check out if this PR's changes fix the "long-lasting" provisioning issue?

**Comment by Raigi** [comment]
Creating primary and secondary devices is a lot faster now, they get provisioned almost immediately.
It takes about 20 seconds. :+1:

**Comment by Raigi** [comment]
Please ignore or remove the atsjenkins comments, I just needed a pull request to test out my script

**Comment by patrickvacek** [comment]
I've been trying to get CI to pass on this but it keeps failing. @mike-sul can you look into that when you have a chance? This looks good and I'd like to merge it.

**Comment by mike-sul** [comment]
> I've been trying to get CI to pass on this but it keeps failing. @mike-sul can you look into that when you have a chance? This looks good and I'd like to merge it.

OK, at first glance it looks odd, will look into it today.

**Comment by mike-sul** [comment]
@patrickvacek It passed now, although I just pressed retry. I don't guarantee that it will work all the time as there is the known design flow in Primary Secondary discovery. You know my idea of the proper solution to address it. Meanwhile, I'll see if it's possible to come up with another quick workaround for this issue.

**Pull request merged**
