### PR TITLE
Feat/backport from master

### PR DESCRIPTION
**Pull request by patrickvacek**
Pull in some recent changes to keep master closer to rocko.

### CODE REVIEW

**Comment by cajun-rat** [comment]
(Rebased)

**Comment by cajun-rat** [comment]
I've dropped the commit that removed the Uptane repo between build steps, because that is dangerous from a security point of view.

**Comment by rsalveti** [comment]
> I've dropped the commit that removed the Uptane repo between build steps, because that is dangerous from a security point of view.

Isn't it more dangerous to let the uptane repo in the deploy folder?

We noticed this because we publish all the files that are available in the deploy/machine folder (output of the build process), and the update repo ended up being published as a consequence.

**Comment by rsalveti** [comment]
Maybe change from deploy to staging instead?

**Comment by patrickvacek** [comment]
Unrelated to the rest of the conversation: I suspect that there are other things in master that should get backported, but I didn't know what all was worth keeping. Once we make a sumo branch, it should presumably have everything from master and rocko.

**Comment by cajun-rat** [comment]
The idea was to improve the security by persisting the Uptane repository state. Since the basic operation of garage-sign is to fetch the existing repository from the server; add the new image; sign it and re-upload it, there is clearly a risk here that the tool might put it's signature on some malicious data provided by the server.

Thinking about this a bit more I'm not convinced persisting this data actually adds anything to the security: the keys are fixed anyway because they come from credentials.zip, and targets.json is going to be fetched and validated against the targets key in both cases.

I think for now I'll add that commit back into this PR, and we can consider changing garage-sign to not require any state for the 'add to targets.json' operation.

cc @heartsucker @simao

**Comment by cajun-rat** [comment]
Passed oe-selftest -r updater

**Pull request merged**
