### PR TITLE
aktualizr: Get garage-sign from the new AWS bucket.

### PR DESCRIPTION
**Pull request by patrickvacek**
Depends on https://github.com/advancedtelematic/aktualizr/pull/1619.

### CODE REVIEW

**Comment by patrickvacek** [comment]
I'm confused how this passed... it should've broken on fetching garage-sign, since the new link is empty now.

**Comment by lbonn** [comment]
Probably because of caching. The file and hash haven't changed.

**Comment by patrickvacek** [comment]
> Probably because of caching. The file and hash haven't changed.

Oh yeah, of course!

**Comment by patrickvacek** [comment]
To confirm: failed as expected when testing locally without the benefit of that file being cached.

**Comment by patrickvacek** [comment]
Now depends on https://github.com/advancedtelematic/aktualizr/pull/1622.

**Pull request merged**
