### PR TITLE
Make layer inclusion a neutral operation

### PR DESCRIPTION
**Pull request by OYTIS**
We (AGL and OE in the near future) want our layer to leave all variables/recipes unchanged unless the user directly chooses to inherit "sota" class and enable "sota" DISTRO_FEATURE

### CODE REVIEW

**Comment by cajun-rat** [comment]
Related: PRO-3059

**Comment by cajun-rat** [comment]
Hi Anton,

I'm getting the following error building on qemu:

ERROR: core-image-minimal-1.0-r0 do_image_wic: Function failed: do_image_wic (log file is located at /home/phil/updater/build-qemu/tmp/work/qemux86_64-poky-linux/core-image-minimal/1.0-r0/temp/log.do_image_wic.12812)
ERROR: Logfile of failure stored in: /home/phil/updater/build-qemu/tmp/work/qemux86_64-poky-linux/core-image-minimal/1.0-r0/temp/log.do_image_wic.12812
Log data follows:
| DEBUG: Executing python function set_image_size
| DEBUG: Python function set_image_size finished
| DEBUG: Executing shell function do_image_wic
| Warning: bootloader config not specified, using defaults
| Error: No boot files defined, IMAGE_BOOT_FILES unset


Do we need to change the docs/add something to local.conf?

**Comment by OYTIS** [comment]
Yes, I've removed some protective clause. Now it should work.

**Comment by cajun-rat** [comment]
Built against qemu/minnowboard.  Boots qemu OK

**Pull request merged**
