### PR TITLE
Backport/thud/secondaries and ci improvement

### PR DESCRIPTION
**Pull request by mike-sul**
oe-selftest hasn't been executed yet

### CODE REVIEW

**Comment by lbonn** [comment]
Will need another rebase to remove some of the excess commits (like on rocko)

**Comment by mike-sul** [comment]
> Will need another rebase to remove some of the excess commits (like on rocko)

is there a plan to merge ci/thud into the thud branch at first, so I can rebase from it  ?

**Comment by lbonn** [comment]
Yes, probably as soon as the tests pass there. Hopefully today.

**Comment by mike-sul** [comment]
@lbonn @patrickvacek Please, verify if it has the desired set of commits/cherrypicks.

**Comment by mike-sul** [comment]
@lbonn @patrickvacek Please, verify if it has the desired set of commits/cherrypicks.

**Comment by mike-sul** [comment]
@lbonn @patrickvacek Please, verify if it has the desired set of commits/cherrypicks.

**Comment by lbonn** [comment]
I think the raspberrypi3-64 changes should be easier to apply here than on rocko, since we use the same boot method. Have you had a try?

**Comment by mike-sul** [comment]
> I think the raspberrypi3-64 changes should be easier to apply here than on rocko, since we use the same boot method. Have you had a try?

Is there any commit into meta-updater related to RPi3-64 support ?

**Comment by lbonn** [comment]
https://github.com/advancedtelematic/meta-updater/commit/80d5f0516c5c6fe9198b0ab767cb7d97cdebcad9

**Comment by mike-sul** [comment]
@lbonn @patrickvacek Please, verify if it has the desired set of commits/cherrypicks.

**Comment by patrickvacek** [comment]
I think this is ready, but I'm curious if the rpi64 part was tested.

Either way, I think QA can take a look if they want. @Raigi this should be tested in tandem with https://github.com/advancedtelematic/meta-updater-raspberrypi/pull/56.

**Pull request merged**
