### PR TITLE
Execute oe-selftest from Gitlab resolves OTA-1937

### PR DESCRIPTION
**Pull request by kmanikandan-kmk**

### CODE REVIEW

**Comment by kmanikandan-kmk** [comment]
Gitlab - Github integration seems to work. The tests run in GitLab are shown in "All checks" section. Currently, only empty script is executed.

**Comment by patrickvacek** [comment]
Cool! I'm willing to trust you here, but can you demonstrate this to me, or is there a way I can see it myself? And is it useful for this integration to merge the almost-empty config file, or should we wait to merge it until it contains some real test specification information?

**Comment by xaviergully** [comment]
@patrickvacek, just look  in the All checks second, and highlith Details
screenshot_2019-01-10 skeleton gitlab configuration by kmanikandan-kmk pull request 455 advancedtelematic meta-updater

**Comment by kmanikandan-kmk** [comment]
> Cool! I'm willing to trust you here, but can you demonstrate this to me, or is there a way I can see it myself? And is it useful for this integration to merge the almost-empty config file, or should we wait to merge it until it contains some real test specification information?

The main idea of this skeleton to check the triggers from GitHub to GitLab and results from GitLab to GitHub.  However, to test GitHub-GitLab integration, we have a PR in aktualizr repo now with GitLab support along with build and tests (https://github.com/advancedtelematic/aktualizr/pull/1049). I will mark this PR as not ready and enable aktualizr PR for review.

**Comment by lbonn** [comment]
Was superseded by #537

**Pull request closed without merging**
