### PR TITLE
Fix incompatibilities with latest pyro, use wic on RPi

### PR DESCRIPTION
**Pull request by OYTIS**
Fixes incompatibilities with changes recently introduced in pyro and meta-raspberrypi. Tested on raspberrypi, we need to test it at least on porter and qemu before merging. Version of meta-raspberrypi in updater-repo might also need to be updated.

UPD:
Homescreen bug is not addressed by this PR.

### CODE REVIEW

**Comment by OYTIS** [comment]
@leon-anavi Could you please test for Porter (that it builds and boots with agl-sota). Our boards are somewhere overseas.

**Comment by leon-anavi** [comment]
OK, I have a porter board. I will test build an image for it and test it.

**Comment by leon-anavi** [comment]
The wic image for porter board (using "nogfx" version with agl-image-minimal) fails to boot due to:

```
U-Boot 2013.01.01-gc4d5d6e (Nov 13 2014 - 17:21:53)

CPU: Renesas Electronics R8A7791 rev 2.0
Board: Porter Board

DRAM:  1 GiB
MMC:   sh-sdhi: 0, sh-sdhi: 1, sh-sdhi: 2
SF: Detected S25FL512S with page size 256 KiB, total 64 MiB
In:    serial
Out:   serial
Err:   serial
Net:   sh_eth
Hit any key to stop autoboot:  0 
Failed to mount ext2 filesystem...
** Unrecognized filesystem type **
Wrong Image Format for bootm command
ERROR: can't get kernel image!
```

I am not sure that uEnv.txt is properly loaded and furthermore I have an older board on which bootmmc have to be set to 2:1. Despite this I believe the GitHub PR should be merged as is. Later on we can continue improving the support of Porter for AGL EE.

Best regards,
Leon

**Comment by cajun-rat** [comment]
Tested the qemu boots too. Merging...

**Pull request merged**
