### PR TITLE
OTA-4388: Conf variable to specify an update type for secondary

### PR DESCRIPTION
**Pull request by mike-sul**
Signed-off-by: Mykhaylo Sul <ext-mykhaylo.sul@here.com>

### CODE REVIEW

**Comment by mike-sul** [comment]
> Looks fine, but we should probably update the doc in aktualizr about local.conf variables used by meta-updater.

In this PR https://github.com/advancedtelematic/aktualizr/pull/1550

**Comment by mike-sul** [comment]
> And what options do we have for testing this? Do we have an oe-selftest that we can expand to cover both cases?

The oe-selftests that we have for IP Secondary test just device provisioning correctly and includes Secondary, but it does not test any update on Secondary.
Or do you mean checking specifically the configuration part, e.g. see if the expected value is in the toml?

**Comment by mike-sul** [comment]
@Raigi you might find this feature interesting for your OTF tests (can choose update type for secondary)

**Comment by Raigi** [comment]
> @Raigi you might find this feature interesting for your OTF tests (can choose update type for secondary)

yes, thank you! :)

**Pull request merged**
