### PR TITLE
Test/oe selftest backport

### PR DESCRIPTION
**Pull request by patrickvacek**
This is just bringing oe-selftest (and grub) in pyro up to speed to lay the groundwork of testing HSM and implicit prov.

### CODE REVIEW

**Comment by patrickvacek** [comment]
@EpicNuts This doesn't really affect actual builds and devices, it's (almost) only a change to our oe-selftest libraries. Test with `oe-selftest -r updater` in your build directory. It takes 10-15 minutes these days.

**Comment by EpicNuts** [comment]
@patrickvacek 
```
bluck@bluck-Precision-7520:/quickpyro_qemu/build$ oe-selftest -r updater
2018-02-14 17:56:31,833 - selftest - INFO - Running bitbake -e to get BBPATH
2018-02-14 17:56:33,180 - selftest - INFO - Checking that everything is in order before running the tests
2018-02-14 17:56:34,224 - selftest - WARNING - meta-selftest layer not found in BBLAYERS, adding it
2018-02-14 17:56:39,361 - selftest - ERROR - Please unset SANITY_TESTED_DISTROS in order to run oe-selftest
```

**Comment by patrickvacek** [comment]
@EpicNuts Ah yes, as it says, you have to set `SANITY_TESTED_DISTROS = ""` in your `local.conf`. It's a bit annoying but that's simply a prerequisite of running oe-selftest.

**Comment by EpicNuts** [comment]
Didn't have "dropbear" dependency. Being added as a requirement in another PR.

**Pull request merged**
