### PR TITLE
Bugfix/update rocko

### PR DESCRIPTION
**Pull request by patrickvacek**
Looks like a lot. Maybe it is. But basically this is everything in pyro that hasn't been ported to rocko. This works for me, although if I used the bleeding-edge aktualizr, it doesn't. I'm still tracking that down, but it shouldn't stop this PR from proceeding.

### CODE REVIEW

**Comment by cajun-rat** [comment]
Testing this on now

**Comment by cajun-rat** [comment]
I get a build error with both ostree and ostree-native when switch between master and this branch.

To reproduce:


    checkout rocko
    bitbake core-image-minimal
    checkout this branch of meta-updater
    bitbake core-image-minimal

I can't copy the error message into this computer at the moment, but it returns some configure error.  bitbake -c clean ostree ostree-native fixes it, but it it the sort of thing that confuses users and I wonder if bumping the PR (package revision, not pull request) in the recipe will fix it?

**Comment by patrickvacek** [comment]
Yeah, this is an annoying problem with bitbake caching. You need to do `bitbake -c cleanall ostree ostree-native` and then `bitbake core-image-minimal` again.

**Comment by patrickvacek** [comment]
@cajun-rat Fixed that issue and the oe-selftest problems.

**Comment by cajun-rat** [comment]
Cool, just trying a build now

**Comment by cajun-rat** [comment]
Tested with a manual update on qemux86-64. It works a charm! I'm seeing a test failures with oe-selftest, but I'll open a separate ticket for that. Having them running is step #1 :)

**Comment by patrickvacek** [comment]
Ah yes, now I see the oe-selftest failures. I'll take a quick look to see if it's easily fixed.

**Pull request merged**
