### PR TITLE
Feat/pro tech #1 rocko

### PR DESCRIPTION
**Pull request by patrickvacek**
Sprint release candidate.

### CODE REVIEW

**Comment by lbonn** [comment]
HSMTests failing (like in #364 I suppose):

```
2018-07-31 17:34:40,034 - oe-selftest - INFO - Traceback (most recent call last):
  File ".../meta-updater/lib/oeqa/selftest/cases/updater.py", line 557, in test_provisioning
    verifyProvisioned(self, machine)
  File ".../meta-updater/lib/oeqa/selftest/cases/updater.py", line 725, in verifyProvisioned
    testInst.assertIn(b'Fetched metadata: yes', stdout, 'Provisioning failed: ' + stderr.decode() + stdout.decode())
AssertionError: b'Fetched metadata: yes' not found in b'Reading config: "/usr/lib/sota/conf.d/20-sota_hsm_prov.toml"\nReading config: "/usr/lib/sota/conf.d/30-implicit_server.toml"\nStorage backend: Filesystem\nDevice ID: soft-herrencreme-675\nPrimary ecu serial ID: b34be278d7e8eedd407650ee485452f8bda1e7355cef5da1cf9bdc414f69f938\nPrimary ecu hardware ID: qemux86-64\nProvisioned on server: yes\nFetched metadata: no\n' : Provisioning failed: Reading config: "/usr/lib/sota/conf.d/20-sota_hsm_prov.toml"
Reading config: "/usr/lib/sota/conf.d/30-implicit_server.toml"
Storage backend: Filesystem
Device ID: soft-herrencreme-675
Primary ecu serial ID: b34be278d7e8eedd407650ee485452f8bda1e7355cef5da1cf9bdc414f69f938
Primary ecu hardware ID: qemux86-64
Provisioned on server: yes
Fetched metadata: no

```

Will investigate...

**Comment by EpicNuts** [comment]
@lbonn shout out when you want me to get this going

**Comment by cajun-rat** [comment]
Looks like the HSM failure is real.  Let's hold off merging this (and the Sumo one) until we can resolve that.

**Comment by lbonn** [comment]
Bisected to https://github.com/advancedtelematic/aktualizr/commit/1ec872af2772ed5fe27acba951e7cb7f2ff9e02e

**Comment by cajun-rat** [comment]
I'm running oe-selftest on #5953082 now...

**Comment by patrickvacek** [comment]
oe-selftest passes for me as well. @EpicNuts can you test, please?

**Comment by patrickvacek** [comment]
So while this fixes one major issue by getting rid of FSStorage, it includes the issue cited at https://github.com/advancedtelematic/aktualizr/issues/899, which we should probably fix and include in this PR before merging.

**Comment by patrickvacek** [comment]
Also note that the latest aktualizr causes a problem with `updater.ManualControlTests.test_manual_running_mode_once` due to FS->SQL migration. I'm looking into it.

**Comment by patrickvacek** [comment]
Updated with the latest aktualizr and a quick (hopefully temporary) fix for the oe-selftest issue. Still checking oe-selftest.

**Comment by patrickvacek** [comment]
Passed oe-selftest on my machine. What other verification do we need to do at this point?

**Pull request merged**
