### PR TITLE
Test for setting hwid

### PR DESCRIPTION
**Pull request by Zee314159**
Rough draft, have not tested yet.

### CODE REVIEW

**Comment by patrickvacek** [comment]
I think this looks pretty good, but something is flaky in CI right now.

**Comment by lbonn** [comment]
A rebase on master could help for CI.

**Comment by lbonn** [comment]
Please do a rebase `git fetch && git rebase origin/master` instead of merging master into the branc.

**Comment by Zee314159** [comment]
> Please do a rebase git fetch && git rebase origin/master instead of merging master into the branch.

Thanks! I'll try it tomorrow.

**Pull request merged**
