### PR TITLE
Update rvi_sota_client to latest commit

### PR DESCRIPTION
**Pull request by taheris**

### CODE REVIEW

**Comment by cajun-rat** [comment]
I get the following build error, does this work for you?

~~~
ERROR: rvi-sota-client-0.2.33-23-g01979ff-r0 do_package: SYSTEMD_SERVICE_rvi-sota-client value sota-client-autoprovision.service does not exist
ERROR: rvi-sota-client-0.2.33-23-g01979ff-r0 do_package: Function failed: systemd_populate_packages
ERROR: Logfile of failure stored in: /home/phil/updater/build-rvi-sota-client/tmp/work/core2-64-poky-linux/rvi-sota-client/0.2.33-23-g01979ff-r0/temp/log.do_package.16328
ERROR: Task (/home/phil/updater/meta-updater/recipes-sota/rvi-sota-client/rvi-sota-client_git.bb:do_package) failed with exit code '1'
~~~

**Comment by taheris** [comment]
Hmm..strange. Yes, I've been building images with it already. Perhaps a cleanall might help, or have you tried that already?

**Comment by cajun-rat** [comment]
I was building from a clean image.  I don't have SOTA_PACKED_CREDENTIALS set, could that be it?

**Comment by taheris** [comment]
Yes, I've tried a build without it and got the same error: `SYSTEMD_SERVICE_rvi-sota-client value sota-client-autoprovision.service does not exist`

**Comment by taheris** [comment]
@cajun-rat: updated to work in the case of no credentials by falling back to the ostree package manager. As discussed, this case depends on manual provisioning by copying the config file to `/sysroot/boot/sota.toml`.

**Comment by taheris** [comment]
@cajun-rat: updated commit to latest master. I spent 15 mins or so yesterday trying to get conditional compilation working for adding the systemd autoprovision service file but was unable to do so. I'll keep it as the old behaviour for now (which means a redundant autoprovision service is deployed in the case of no credentials).

**Comment by cajun-rat** [comment]
Build tested OK.

**Pull request merged**
