### PR TITLE
aktualizr: Get latest for PRO-H#2 sprint. (rocko)

### PR DESCRIPTION
**Pull request by patrickvacek**

### CODE REVIEW

**Comment by patrickvacek** [comment]
Ready to go, I think.

**Comment by cajun-rat** [comment]
I think I've found a bug where the metadata doesn't get upgraded correctly between versions. I'm investigating now.

**Comment by patrickvacek** [comment]
@cajun-rat Crap, that's in aktualizr, though, right? If so, that affects all of the meta-updater branches.

**Comment by cajun-rat** [comment]
Yep.

**Comment by patrickvacek** [comment]
Now includes the metadata fix and a backport of the manual aktualizr update test.

**Comment by patrickvacek** [comment]
Updated for PRO-H#3 sprint.

**Comment by patrickvacek** [comment]
Can @cajun-rat or @EpicNuts merge please?

**Comment by EpicNuts** [comment]
@patrickvacek - no merging on my end

**Pull request merged**
