### PR TITLE
Explicitly include ca-certificates as a dependency for garage-push

### PR DESCRIPTION
**Pull request by cajun-rat**
Fixes: PRO-4254

### CODE REVIEW

**Comment by patrickvacek** [comment]
Okay, this is getting more complicated. I ran `bitbake -c cleanall ca-certificates-native` and deleted the cert file that my garage-push was pointing at (`/home/patrick/Code/qemu_build2/build/tmp/work/qemux86_64-poky-linux/core-image-minimal/1.0-r0/recipe-sysroot-native/etc/ssl/certs/ca-certificates.crt`). Then I got the error you mention. I rebaked ca-certificates-native and still got the error. I switched to this branch, cleaned aktualizr-native, and rebaked  my image, and I still get the error. I cannot get the system to give me a cert at the given location. I do, however, see one at `./tmp/work/qemux86_64-poky-linux/core-image-minimal/1.0-r0/rootfs/etc/ssl/certs/ca-certificates.crt` and another at `./tmp/sysroots-components/x86_64/ca-certificates-native/etc/ssl/certs/ca-certificates.crt`. If I manually ran with the extant certs, it works.

**Comment by patrickvacek** [comment]
@cajun-rat I've updated this with the result of deeper investigation. I'm very curious if it works for you. Also, if it does, should I try to upstream my ca-certificates fix?

**Comment by leon-anavi** [comment]
I explicitly confirm that after rebasing this fix on top of my current AGL branches ostreepush succeeded. Thanks, Leon

**Comment by cajun-rat** [comment]
Works on My Machine™

**Pull request merged**
