### PR TITLE
Backport/thud/garage sign lock etc

### PR DESCRIPTION
**Pull request by patrickvacek**
Actually just pulling master into thud. A couple commits are redundant, but this is still easier than cherry-picking.

### CODE REVIEW

**Comment by lbonn** [comment]
Shouldn't this PR be against thud? Looks like github wants to merge it in master.

**Comment by patrickvacek** [comment]
> Shouldn't this PR be against thud? Looks like github wants to merge it in master.

Oops, user error. Thanks for catching that. I knew the list of commits didn't look complete, but I hadn't yet gotten around to figuring out why.

**Comment by patrickvacek** [comment]
> (didn't run test)

I'm still waiting on oe-selftest, and I'm also working on the rocko/sumo backports.

**Comment by patrickvacek** [comment]
Passes oe-selftest!

**Pull request merged**
