### PR TITLE
Remove redundant doc material.

### PR DESCRIPTION
**Pull request by patrickvacek**
~~Some of this content was moved from the contrib doc.~~

~~Also covers the considerations of changing release branches.~~

~~Replacement PR for https://github.com/advancedtelematic/aktualizr/pull/1330.~~

~~Still not connected to the navigation system; I wasn't sure how to make that work.~~

### CODE REVIEW

**Comment by xaviergully** [comment]
@patrickvacek Good idea to have a separate page for the supported yocto branch. 
Having this information in the contributing section was difficult to find

**Comment by merltron** [comment]
Ok, so the thing is...

The nav lives in the aktualizr repo.
https://github.com/advancedtelematic/aktualizr/blob/master/docs/ota-client-guide/modules/ROOT/nav.adoc

You could add a 'xref' in the "For contributors" section down the bottom, but you'd need to do a "cross-repo xref" (which is another argument for keeping meta-update doc *also* in the aktualizr repo)

In antora, a cross repo xref looks like this `* xref:dev@ota-client::yocto-release-branches.adoc[Yocto release branches]`
But this wont work in GitHub (if you happen to use the TOC).

To make it work you could:
- Put this topic in the aktualizr repo where you originally had it (where relative links are possible)
- Keep this topic in meta-updater and add a conditional statement in the nav that points to "https://github.com/advancedtelematic/meta-updater/tree/master/docs/modules/ROOT/pages/yocto-release-branches.adoc"

**Comment by patrickvacek** [comment]
> Put this topic in the aktualizr repo where you originally had it (where relative links are possible)

To summarize our conversation: we're going down this road. I've reopened https://github.com/advancedtelematic/aktualizr/pull/1330 and updated it with changes from here.

This PR will stay open for now just with the change to remove the redundant part. It should actually get updated to point at the right place in the docs portal once it is there, so don't merge this until it is ready.

**Comment by merltron** [comment]
Ok removed all redundant content and fixed some xrefs to point to future locations in the aktualizr repo

**Comment by patrickvacek** [comment]
> I'm kind of approving my own changes here...but LGTM

That's fine -- although I did just correct a typo. We should wait to merge until https://github.com/advancedtelematic/aktualizr/pull/1332 is merged and we can clean up and/or reorganize the README a bit more.

**Comment by merltron** [comment]
RE: [the latest commit ](https://github.com/advancedtelematic/meta-updater/pull/595/commits/cfbcae869ba628f3e1720aad7c2f0c150302f40d)

I don't think the heading "== Table of Contents" makes much sense now that there's content sandwiched between it and the actual TOC (now with the header "Further Documentation). I would move that "== Table of Contents" block to where it now says "Further Documentation" (replace it)

**Comment by patrickvacek** [comment]
> I don't think the heading "== Table of Contents" makes much sense now that there's content sandwiched between it and the actual TOC (now with the header "Further Documentation). I would move that "== Table of Contents" block to where it now says "Further Documentation" (replace it)

Oops, that did look bad. Fixed, I think. See what you think now.

**Comment by merltron** [comment]
thanks. I approve!

**Pull request merged**
