### PR TITLE
Upgrade to Pyro

### PR DESCRIPTION
**Pull request by chbae**
I'm working for AGL (Automotive Grade Linux) and we should rebase meta-update.

### CODE REVIEW

**Comment by cajun-rat** [comment]
Nice, thank you.  Do you happen to know if this is backwards compatible with morty?  Otherwise I'll create a pyro branch for it.

**Comment by chbae** [comment]
This PR isn't applied morty because 392532a2748ff2e6412eeb79163662b5168611ce (wic: move oe/misc.py one level up) came from pyro.

**Comment by cajun-rat** [comment]
OK.  I've created a 'pyro' branch on meta-updater.  I can't see how to change the target branch of a PR from my side--could you change it to point at 'pyro', please?

I'm also happy to just do this from the git command line, but it feels nicer to merge your PR :)

**Comment by chbae** [comment]
@cajun-rat After you create pyro branch and then I'll create PR again. Thanks.

**Comment by cajun-rat** [comment]
@chbae  Should be available here: https://github.com/advancedtelematic/meta-updater/tree/pyro

**Pull request closed without merging**
