### PR TITLE
Increase time to wait for secondaries registration at Primary

### PR DESCRIPTION
**Pull request by mike-sul**
Signed-off-by: Mike Sul <ext-mykhaylo.sul@here.com>

### CODE REVIEW

**Comment by patrickvacek** [comment]
Seems fine. Have you been seeing problems in CI or elsewhere?

**Comment by mike-sul** [comment]
> Seems fine. Have you been seeing problems in CI or elsewhere?

@lbonn Laurent have been seeing it while working on CI pipelines for meta-updater/oe-selftests

**Comment by patrickvacek** [comment]
Cool, yeah, I saw the ticket in his PR too. Do you want to merge this now or leave it for that PR?

**Comment by mike-sul** [comment]
> Cool, yeah, I saw the ticket in his PR too. Do you want to merge this now or leave it for that PR?

I'd prefer to merge it now.

**Pull request merged**
