### PR TITLE
Fit initramfs support

### PR DESCRIPTION
**Pull request by cajun-rat**

### CODE REVIEW

**Comment by cajun-rat** [comment]
Copy of #360 .

**Comment by cajun-rat** [comment]
@Jmennius I rebased your commits and added back in that dependency

**Comment by patrickvacek** [comment]
Everything passes except for HSM (go figure): `AssertionError: 0 == 0 : softhsm2-tool succeeded before initialization`. I don't understand how that's possible, but if you want me to look into it, I can get around to it sooner or later.

**Comment by cajun-rat** [comment]
Rebased onto latest master

**Comment by cajun-rat** [comment]
The tests now pass on my machine

**Comment by Jmennius** [comment]
I am glad this worked out (considering some testing shortcomings of mine..)!

I suppose it works w/o advancedtelematic/meta-updater-raspberrypi#25?
If true - we can probably close that pull, as it will also allow to boot with external initramfs?

**Comment by patrickvacek** [comment]
@Jmennius Yes, I didn't test it with the raspberry-pi PR, so if you no longer need that, feel free to close it.

We still need to test https://github.com/advancedtelematic/meta-updater-raspberrypi/pull/24, although it doesn't actually look like it should be a big change.

**Pull request merged**
