### PR TITLE
Properly install example-interface on target and remove it on host.

### PR DESCRIPTION
**Pull request by patrickvacek**
Not ready yet since we will also want to bump the aktualizr version once https://github.com/advancedtelematic/aktualizr/pull/437 is merged.

### CODE REVIEW

**Comment by OYTIS** [comment]
@patrickvacek 
I would let user enable/disable installation of example interface with some SOTA_CLIENT_FEATURE.

**Comment by OYTIS** [comment]
@patrickvacek And the version of aktualizr also needs to be bumped.

**Comment by patrickvacek** [comment]
> I would let user enable/disable installation of example interface with some SOTA_CLIENT_FEATURE.

I was wondering about that. I took the easy route for now but that seems reasonable.

**Comment by OYTIS** [comment]
Let's merge it before the demo time and then add the options. I have a local branch for that on my machine, just don't want to do all the testing right now.

**Comment by patrickvacek** [comment]
Cool, give me just a minute to update this...

**Comment by patrickvacek** [comment]
@OYTIS Look ready to you?

**Comment by patrickvacek** [comment]
Rebased and updated with the proper fix for only installing example-interface if explicitly requested.

**Pull request merged**
