### PR TITLE
meta: support readonly sysroot

### PR DESCRIPTION
**Pull request by liuming50**
Currently ostree sysroot is being mounted as RW by ostree-remount
systemd service, add a variable OSTREE_SYSROOT_READONLY to control
that, so the end users could choose to mount sysroot as RO.

Signed-off-by: Ming Liu <liu.ming50@gmail.com>

### CODE REVIEW

**Review by pattivacek — APPROVED** [review]
LGTM!

**Comment by sergioprado** [comment]
@pattivacek moving forward, should we submit PRs here or in the uptane space?

**Comment by pattivacek** [comment]
@sergioprado in the long term, I think moving towards the Uptane namespace is preferred. I no longer work for ATS/Here and I've been busy with other things, but for now I'm still keeping an eye on both. AFAIK the testing infrastructure at Here isn't in a great place at present, and since it was never publicly visible anyway, I'd like it if we could somehow get a better setup in place. I think the Uptane namespace would be a better place to do that work.

**Comment by sergioprado** [comment]
That sounds great @pattivacek. I guess this is also valid for other repositories like aktualizr. Moving forward, we will send PRs against the Uptane namespace. Thanks!

**Comment by ricardosalveti** [comment]
> That sounds great @pattivacek. I guess this is also valid for other repositories like aktualizr. Moving forward, we will send PRs against the Uptane namespace. Thanks!

Shouldn't we free the ones from advancedtelematic then? Or make one a mirror from the other?

Having two active projects/branches is quite confusing :-)

**Comment by pattivacek** [comment]
> Shouldn't we freeze the ones from advancedtelematic then? Or make one a mirror from the other?
> 
> Having two active projects/branches is quite confusing :-)

Yes, probably. I don't think I can make that change, though, and if Here continues to use the advancedtelematic namespace, I can't stop them. I would prefer to unify in the uptane namespace and I would love it if we could have some testing infrastructure around that.

**Pull request merged**
