### PR TITLE
Split Aktualizr binary and systemd service/configuration

### PR DESCRIPTION
**Pull request by leon-anavi**
Split Aktualizr binary and systemd service and configurations in two separate Yocto/OE recipes:
* aktualizr that provides the binary
* aktualizr-pro that provides the systemd services and configurations for manual or autoprovision of Aktualizr.

Best regards,
Leon

### CODE REVIEW

**Comment by patrickvacek** [comment]
This looks good and works for me. My only request would be that we name the new autoprov configuration recipe something like "aktualizr-auto-prov", since this is a precursor to adding a new implicit provisioning configuration recipe that will probably be named something like "aktualizr-implicit-prov". I'm open to other schemes, though.

**Comment by leon-anavi** [comment]
@patrickvacek  thank you for the feedback. I have renamed the recipe to **bitbake rpi-basic-image**.

**Comment by patrickvacek** [comment]
@leon-anavi copy-paste error? :)

**Comment by patrickvacek** [comment]
Hooray, I can merge now!

**Pull request merged**
