### PR TITLE
Backport/sumo/secondaries and ci improvement

### PR DESCRIPTION
**Pull request by mike-sul**

### CODE REVIEW

**Comment by mike-sul** [comment]
oe-selftest hasn't been executed yet

**Comment by lbonn** [comment]
Will need another rebase to remove some of the excess commits (like on rocko)

**Comment by mike-sul** [comment]
> Will need another rebase to remove some of the excess commits (like on rocko)

is there a plan to merge ci/sumo into the sumo branch at first, so I can rebase from it  ?

**Comment by mike-sul** [comment]
Locally the tests have passed
2019-07-19 13:50:59,378 - oe-selftest - INFO - oe-selftest - OK - All required tests passed (successes=17, skipped=0, failures=0, errors=0)

I suppose, it would be great to do manual verification on RPi.

**Comment by mike-sul** [comment]
@lbonn @patrickvacek Please, verify if it has the desired set of commits/cherrypicks.

**Comment by mike-sul** [comment]
@lbonn @patrickvacek Please, verify if it has the desired set of commits/cherrypicks.

**Comment by patrickvacek** [comment]
@mike-sul Yes, I think this looks good. I was just waiting for QA on rocko in case anything came up. Rocko and sumo are pretty similar, so anything that comes up there will probably affect this, too.

**Pull request merged**
