### PR TITLE
Stop forcing Linux 4.4 on qemux86-64

### PR DESCRIPTION
**Pull request by lbonn**
The mentioned issue doesn't seem to exist anymore

### CODE REVIEW

**Comment by lbonn** [comment]
Precision: I ran `oe-selftest -r updater`and only had failures on the rpi tests (should probably check those anyway).

**Comment by patrickvacek** [comment]
> I ran oe-selftest -r updaterand only had failures on the rpi tests

What were the errors? It's possible that the test is not robust, but it's also possible that the linux-4.4 issue was because of rpi in the first place.

**Comment by lbonn** [comment]
I'll relaunch a test but since the change is in `sota_qemux86-64.bbclass`, it shouldn't have an influence.

Here is the commit that introduces the version freeze: https://github.com/advancedtelematic/meta-updater/commit/a42822fe5d4351a64c4a589756f7b72c81b8f2ef

**Comment by patrickvacek** [comment]
> Everything passed this time

Glad to hear it. Have you tested with an rpi? It worked for me as well with qemu, but I'd like to make sure that someone has tested booting an rpi with this.

**Comment by lbonn** [comment]
@patrickvacek you really think it's necessary, even though the only change is in `sota_qemux86-64.bbclass`? We're compiling 4.9.xx kernels from meta-raspberrypi, just like before.

**Pull request merged**
