### PR TITLE
aktualizr: Upgrade to 2020.10 release

### PR DESCRIPTION
**Pull request by aodukha**
aktualizr: Upgrade to 2020.9 release.
Signed-off-by: Anatoliy Odukha <aodukha@gmail.com>

### CODE REVIEW

**Comment by patrickvacek** [comment]
I haven't touched master in a while, but if you want to update it, I would recommend forward-porting some of the recent changes that were merged directly to dunfell.

**Comment by patrickvacek** [comment]
Specifically, I think this (and the other branches except dunfell) are missing the commits from https://github.com/advancedtelematic/meta-updater/pull/775.

Also, I don't see a PR for thud. I think we still have to support that for now, although maybe not forever.

**Comment by patrickvacek** [comment]
Looks fine, but it's not great to use the merge commit; I prefer cherry-picking the individual commits from #775. Not a blocker, but it makes it a lot easier to compare what commits are where. The DCO check also isn't critical here, but normally I do `rebase master --signoff` to deal with that.

**Comment by aodukha** [comment]
pushed cleaner version.

**Review by patrickvacek — APPROVED** [review]
LGTM. It'd be good to have CI running smoothly again, though.

**Comment by aodukha** [comment]
> LGTM. It'd be good to have CI running smoothly again, though.

eh... I added ticket for this (OTA-5338)
Really configs are inconsistent and bitbake cannot build images. Probably #778 is responsible for the first error. Because other layers do not have gatesgarth.

**Comment by patrickvacek** [comment]
> I added ticket for this (OTA-5338)

Sounds good, but I don't think that's the right ticket.

> Really configs are inconsistent and bitbake cannot build images. Probably #778 is responsible for the first error. Because other layers do not have gatesgarth.

Yeah, that's not helping. I think the RPi problems are still open issues here, too.

**Pull request merged**
