### PR TITLE
classes: image_types_ostree: use locking during OSTree repo update

### PR DESCRIPTION
**Pull request by agners**
The OSTree repository might be shared accross several individual
OSTree builders. Use bitbakes lockfiles mechanism to lock the
OSTree for exclusive use.

Signed-off-by: Stefan Agner <stefan.agner@toradex.com>

### CODE REVIEW

**Comment by agners** [comment]
Actually that causes an issue when building the first time: If $OSTREE_REPO does not exist, lockfiles will create it. However, the `do_image_ostree` task uses the directory to detect whether to initialize an OSTree repo:

     if [ ! -d ${OSTREE_REPO} ]; then
         ostree --repo=${OSTREE_REPO} init --mode=archive-z2
     fi

This is not ideal anyway, I think we should use some better method to detect whether there is a OSTree repo already.

**Comment by patrickvacek** [comment]
@agners Nice, I like the look of this! I'm testing it now.

Fixes #412.

**Comment by OYTIS** [comment]
@agners Thanks, looks great. Do you know if this mechanism is documented somewhere?

**Comment by patrickvacek** [comment]
Passes oe-selftest, I'm just checking things once more before merging.

**Comment by lbonn** [comment]
@OYTIS from the mailing list thread: https://www.yoctoproject.org/docs/latest/bitbake-user-manual/bitbake-user-manual.html#variable-flags

**Pull request merged**
