### PR TITLE
Bump Aktualizr to get PRO-5211 Report network info

### PR DESCRIPTION
**Pull request by cajun-rat**

### CODE REVIEW

**Comment by cajun-rat** [comment]
FYI @jerrytrieu

**Comment by lbonn** [comment]
Note that we diverged a bit from our usual procedure: the pyro branch has more features (allows disabling the telemetry)

https://github.com/advancedtelematic/meta-updater/pull/303/files#diff-f2aae02cbe4ce1c4286c7b37609f8403

That's probably not the long-term proper way to support that though...

**Comment by patrickvacek** [comment]
> That's probably not the long-term proper way to support that though...

See https://advancedtelematic.atlassian.net/browse/PRO-5297, which I'm looking into right now.

**Comment by EpicNuts** [comment]
@patrickvacek Nope, no reason :)

**Pull request merged**
