### PR TITLE
Feature/rollback forwardport

### PR DESCRIPTION
**Pull request by lbonn**
This feature was originally developed on rocko.

It would probably be worthwhile to write oe-selftests for that.

### CODE REVIEW

**Comment by patrickvacek** [comment]
> It would probably be worthwhile to write oe-selftests for that.

Agreed, but how? We'd need to automate boot failure somehow, and also manage to install an update with oe-selftest, which we haven't done yet. Maybe it's possible with aktualizr-repo?

**Comment by lbonn** [comment]
Yes, that's not easy. We would also need to run raspberry pi on Qemu or port the feature to qemux86-64...

Still some challenges on the road.

**Comment by patrickvacek** [comment]
oe-selftest is failing on HSM, which can be fixed with a rebase, and rpi due to this: `ERROR: aktualizr-uboot-env-rollback-1.0-r0 do_fetch: Fetcher failure for URL: 'file://LICENSE'. Unable to fetch URL from any source.`

That aside, how do we test this (manually) to verify that it works?

**Comment by patrickvacek** [comment]
I also get this failure on the Primary test, although I don't really understand it: `ERROR: When reparsing virtual:native:/home/patrick/Code/updater_repo_master/meta-updater/recipes-sota/aktualizr/aktualizr_git.bb.do_configure, the basehash value changed from 98e314800b4f35f1a90b737d86669cb8 to 8533005548d8a7462e751bee93ca2cf7. The metadata is not deterministic and this needs to be fixed.`

**Comment by lbonn** [comment]
No idea how the license check worked on rocko.

**Comment by patrickvacek** [comment]
oe-selftest passes, but I still need to manually verify that this works. Can we do this together? (Or if @OYTIS knows how to do it, that's fine, too.)

**Comment by lbonn** [comment]
@patrickvacek you were right to ask for a test, because we forgot to merge the required part in meta-updater-raspberrypi :)

**Comment by patrickvacek** [comment]
@lbonn Crud. Are you looking into that for sumo and master? Or if you'd prefer, I can make the PRs but I still don't know how to actually test the functionality.

**Pull request merged**
