### PR TITLE
Backport/rocko/auto reboot etc

### PR DESCRIPTION
**Pull request by patrickvacek**
* Bump to latest aktualizr.
* Add recipe for automatic reboot after installation.
* More robust fix for simultaneous bitbaking.
* Remove API Gateway URL if present before putting credentials on a device.

### CODE REVIEW

**Comment by patrickvacek** [comment]
Passes oe-selftest.

**Comment by EpicNuts** [comment]
Can we add it to the README.md, under the "SOTA-related variables in local.conf" section?

**Comment by patrickvacek** [comment]
@EpicNuts I'll add it to the [aktualizr configuration](https://github.com/advancedtelematic/meta-updater/#aktualizr-configuration) section. I'd forgotten about that and that is the perfect place for it.

**Comment by patrickvacek** [comment]
@EpicNuts Done. What do you think of https://github.com/advancedtelematic/meta-updater/blob/cfd16dc98ad78a724372b42056b3a94583743d36/README.adoc#aktualizr-configuration?

**Comment by EpicNuts** [comment]
Perfect :)
Tested on a Qemu with a couple of Campaigns, and a Raspberry Pi with a couple of single-updates.
Raigi gave it a thumbs up too, so I'm gonna slap that merge button

**Pull request merged**
