### PR TITLE
Fix harmless error from not installing garage_deploy.

### PR DESCRIPTION
**Pull request by patrickvacek**

### CODE REVIEW

**Comment by patrickvacek** [comment]
At what point is it worth explicitly specifying what files we want to install on the device and host instead of explicitly deleting those that we don't want?

**Comment by cajun-rat** [comment]
Random question: what about pulling this stuff into a separate package like 'aktualizr-tools' or 'aktualizr-extras'?

**Comment by patrickvacek** [comment]
> Random question: what about pulling this stuff into a separate package like 'aktualizr-tools' or 'aktualizr-extras'?

Wouldn't that mean recompiling aktualizr multiple times for each package?

I'm not particularly bothered by the current layout, just that there isn't an easy way to say "don't bother with x and y".

**Comment by cajun-rat** [comment]
Nah, it it possible to have multiple RPMs from a single package.  The syntax is quite simple (I'll have to big up an example when I have a second), and isn't really any more complex than rm-ing the files we don't need.

**Comment by cajun-rat** [comment]
Tested with an update on qemu against the production server

**Pull request merged**
