### PR TITLE
Add universal uEnv recipe

### PR DESCRIPTION
**Pull request by OYTIS**
Signed-off-by: Anton Gerasimov <anton.gerasimov@here.com>

### CODE REVIEW

**Comment by OYTIS** [comment]
It is an attempt to make a platform-independent uEnv.txt script supporting rollbacks and FIT images. The primary purpose here is that instead of pointing people integrating this layer with their boards to https://github.com/advancedtelematic/meta-updater-raspberrypi provide some framework that could be adjusted to different boards.

It's hard to tell right now how universal it really is, because the only U-Boot board we have in master is Raspberry Pi, but I hope it will not be hard to make some adjustments if problems arise.

I've tested it in the default mode, that is using FIT and rollback functionality, and with some adjustments without FIT as well (a few other variables need to be changed in sota_raspberrypi.bbclass, like the type of kernel image for instance). I didn't test the rollback functionality itself (yet). It would be also nice to extend it to support Qemu as well, the blocker here is that there is no boot partition in Qemu case now, `otaimg` gets booted directly.

Also it looks like the selftest for Grub is failing again, because I had to make `INITRAMFS_IMAGETYPES` an overlay again. I'll try to look into that.

**Comment by OYTIS** [comment]
Update: rollback works.

**Comment by OYTIS** [comment]
Configuration with rollback disabled works as well (apart from the rollback functionality of course). So only the Grub test issue is left.

**Comment by agners** [comment]
Can we not just mandate using distro boot? Distro boot passes a lot of variables to the boot script which then can be reused.

**Comment by ricardosalveti** [comment]
I also find quite weird to have defaults for values that are really platform specific, and most are already provided by the bootloader (and distro boot).

Shouldn't we just rely on what gets provided by the bootloader instead?

**Comment by OYTIS** [comment]
@ricardosalveti @agners 

Thank you for your comments and sorry for the delay. As far as I remember, the FIT image for raspberrypi couldn't fit at `kernel_addr_r` and I had to relocate it to `ramdisk_addr_r`. Therefore I had that idea that ostree-related variables should be decoupled from distro boot variables.

Maybe that was a transient bug and is not really the case any more, I'll try to test that ASAP and if possible then would be happy to remove these extra variables.

**Comment by OYTIS** [comment]
@ricardosalveti @agners @patrickvacek 

Sorry for the delay. Just rechecked - there's really a problem with loading FIT image to `kernel_addr_r` in that it overlaps with unpacked kernel. `ramdisk_addr_r` works well. So `SOTA_BOOTLOADER_*_ADDR` are apparently needed. One improvement I can suggest is to set them by default to distro boot counterparts.

**Comment by lbonn** [comment]
I'll just close this for now as it hasn't been active for a long time and we still haven't agreed on how/whether to do this.

Feel free to reopen if needed.

**Comment by OYTIS** [comment]
Nooooo!
Well, it wasn't a huge success anyway.

**Pull request closed without merging**
